# Generated by Django 4.2 on 2023-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testttt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField()),
                ('last_modified_date_time', models.DateTimeField()),
                ('img_src', models.CharField(max_length=255)),
                ('dtype', models.CharField(max_length=31)),
            ],
        ),
    ]
