# Generated by Django 4.2 on 2023-04-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0002_testttt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='painting',
        ),
        migrations.DeleteModel(
            name='testttt',
        ),
    ]
